// Author: Microsoft Azure
// Display name: Firewall request count by host, path, rule, and action
// Description: Count firewall processed requests by host, path, rule, and action taken.
// Categories: Network,Security
// Resource types: Front Doors
// Topic: Firewall Audit

// Summarize request count by host, path, rule, and action
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.NETWORK" and Category == "FrontdoorWebApplicationFirewallLog"
| extend ParsedUrl = parseurl(requestUri_s)
| summarize RequestCount = count() by Host = tostring(ParsedUrl.Host), Path = tostring(ParsedUrl.Path), RuleName = ruleName_s, Action = action_s 
| order by RequestCount desc