// Author: Microsoft Azure
// Display name: Top 5 Clients
// Description: Top 5 clients which are generating traffic.
// Categories: Azure Resources
// Resource types: App Services
// Topic: Incoming requests

AppServiceHTTPLogs
| top-nested of _ResourceId by dummy=max(0), // Display results for each resource (App)
  top-nested 5 of UserAgent by count()
| project-away dummy // Remove dummy line from the result set