// Author: Microsoft Azure
// Display name: Failed requests per hour
// Description: Count of requests to which Application Gateway responded with an error.
// Categories: Network
// Resource types: Application gateways
// Topic: Incoming requests

AzureDiagnostics
| where ResourceType == "APPLICATIONGATEWAYS" and OperationName == "ApplicationGatewayAccess" and httpStatus_d > 399
| summarize AggregatedValue = count() by bin(TimeGenerated, 1h), _ResourceId
| render timechart