// Author: Microsoft Azure
// Display name: Review audit log events
// Description: Identify audit events for your server.
// Categories: Workloads,Audit
// Resource types: Azure Database for MySQL servers
// Topic: Audit

AzureDiagnostics
| where ResourceProvider =="MICROSOFT.DBFORMYSQL"
| where Category == 'MySqlAuditLogs'
| project TimeGenerated, LogicalServerName_s, event_subclass_s, event_time_t, user_s , ip_s , sql_text_s 
| order by TimeGenerated asc