// Author: Microsoft Azure
// Display name: All logs with level "Error"
// Description: Shows all logs that are likely to have negatively impacted your job.
// Categories: Azure Resources
// Resource types: Stream Analytics jobs
// Topic: Other errors and failures

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS" and Level == "Error" 
| project TimeGenerated, Resource, Region_s, OperationName, properties_s, Level