// Author: Microsoft Azure
// Display name: Summary of all errors in the last 7 days
// Description: Summary of all errors in the last 7 days.
// Categories: Azure Resources
// Resource types: Stream Analytics jobs
// Topic: Other errors and failures

AzureDiagnostics
| where TimeGenerated > ago(7d) //last 7 days
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS"
| extend ErrorType = tostring(parse_json(properties_s).Type)
| summarize Count=count(), sampleEvent=any(properties_s)  by ErrorType, JobName=Resource