// Author: Microsoft Azure
// Display name: Windows Firewall policy settings changed by machines
// Description: Windows Firewall policy settings changed by machines.
// Categories: virtualmachines
// Solutions: LogManagement
// Topic: Diagnostics

Event 
| where EventLog == "Microsoft-Windows-Windows Firewall With Advanced Security/Firewall" and EventID == 2008 
| summarize count() by Computer 
| limit 10000
