// Author: Microsoft Azure
// Display name: Computers With Failed Linux User Password Change
// Description: Lists computers wih failed Linux user password change.
// Categories: security
// Solutions: SecurityInsights
// Topic: Security

Syslog
| where Facility == 'authpriv' and ((SyslogMessage has 'passwd:chauthtok' and SyslogMessage has 'authentication failure') or SyslogMessage has 'password change failed')
| summarize count() by Computer