// Author: Microsoft Azure
// Display name: Show the config server logs
// Description: Filter the config server logs with the log level.
// Categories: Azure Resources
// Resource types: Azure Spring Cloud
// Topic: System Logs

AppPlatformSystemLogs 
| where TimeGenerated > ago(1h)
| where LogType == "ConfigServer" and Level in ("WARN", "ERROR")
| project TimeGenerated , Level , ServiceName , Thread , Stack , Log , _ResourceId