// Author: Microsoft Azure
// Display name: Chart of daily received snapshots
// Description: A time chart of the daily snapshots count, over the past week.
// Categories: Audit
// Resource types: Data Shares
// Topic: Audit

// Failed, In Progress and Succeeded Received Snapshots
MicrosoftDataShareReceivedSnapshotLog 
| where TimeGenerated > ago(7d)  
| summarize count() by bin(TimeGenerated, 1d), Status , _ResourceId // Aggregating by day //Click "Table" to see resource's name.
| render timechart