// Author: Microsoft Azure
// Display name: Chat Operational Errors
// Description: List every Chat error ordered by recency.
// Categories: Azure Resources
// Resource types: Communication Services
// Topic: Errors

ACSChatIncomingOperations
| where ResultType == "Failed"
| project TimeGenerated, OperationName, OperationVersion, ResultSignature, ResultDescription
| order by TimeGenerated desc