// Author: Microsoft Azure
// Display name: List all ColumnNameInvalid errors
// Description: Shows errors where the output record produced by your job has a column name that doesn't map to a column in your output.
// Categories: Azure Resources
// Resource types: Stream Analytics jobs
// Topic: Output data errors

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS" and parse_json(properties_s).DataErrorType == "OutputDataConversionError.ColumnNameInvalid"
| project TimeGenerated, Resource, Region_s, OperationName, properties_s, Level