// Author: Microsoft Azure
// Display name: List all DuplicateKey errors
// Description: Shows errors where the output record produced by job contains a column with the same name as a System column.
// Categories: Azure Resources
// Resource types: Stream Analytics jobs
// Topic: Output data errors

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS" and parse_json(properties_s).DataErrorType == "OutputDataConversionError.DuplicateKey"
| project TimeGenerated, Resource, Region_s, OperationName, properties_s, Level