// Author: Microsoft Azure
// Display name: Top 10 longest time range queries
// Description: Get top 10 queries that scanned the longest time range in last 24 hours.
// Categories: Audit,Azure Monitor
// Resource types: Log Analytics workspaces
// Topic: Audit

LAQueryLogs
| extend DataProcessedTimeRange = format_timespan(StatsDataProcessedEnd - StatsDataProcessedStart, 'dd.hh:mm:ss:FF')
| top 10 by DataProcessedTimeRange desc nulls last