// Author: Microsoft Azure
// Display name: Show the Slowest queries
// Description: Identify top 5 slowest queries.
// Categories: Workloads
// Resource types: Azure Database for MySQL servers
// Topic: Performance

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.DBFORMYSQL" 
| where Category == 'MySqlSlowLogs'
| project TimeGenerated, LogicalServerName_s, event_class_s, start_time_t , query_time_d, sql_text_s 
| top 5 by query_time_d desc