// Author: Microsoft Azure
// Display name: Bottom 10 Free disk space %
// Description: Bottom 10 Free disk space % by computer, for the last 7 days.
// Categories: Virtual Machines
// Resource types: Virtual machines
// Topic: Performance

Perf
| where TimeGenerated > ago(7d)
| where (ObjectName == "Logical Disk" or ObjectName == "LogicalDisk") and CounterName contains "%" and InstanceName != "_Total" and InstanceName != "HarddiskVolume1"
| project TimeGenerated, Computer, ObjectName, CounterName, InstanceName, CounterValue 
| summarize arg_max(TimeGenerated, *) by Computer
| top 10 by CounterValue desc