// Author: Microsoft Azure
// Display name: Logical disk space % below threshold:
// Description: Show avg % of free Logical disk space over 10 minutes.
// Categories: Virtual Machines
// Resource types: Virtual machines
// Topic: Performance

let _minValue = 10; // Set the minValue according to your needs
Perf
| where ObjectName == "LogicalDisk" and CounterName == "% Free Space" // the object name used in Windows records
| where TimeGenerated >= ago(30m) // choose time to observe 
| where CounterValue <= _minValue
| summarize avg(CounterValue) by bin(TimeGenerated, 10m), Computer, InstanceName