// Author: Microsoft Azure
// Display name: Events that arrived early
// Description: Shows errors due to events where difference between Application time and Arrival time is greater than 5 minutes.
// Categories: Azure Resources
// Resource types: Stream Analytics jobs
// Topic: Input data Errors

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS" and parse_json(properties_s).DataErrorType == "EarlyInputEvent"
| project TimeGenerated, Resource, Region_s, OperationName, properties_s, Level