// Author: Microsoft Azure
// Display name: List all InvalidInputTimeStamp errors
// Description: Shows errors caused due to events where value of the TIMESTAMP BY expression can't be converted to datetime.
// Categories: Azure Resources
// Resource types: Stream Analytics jobs
// Topic: Input data Errors

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS" and  parse_json(properties_s).DataErrorType == "InvalidInputTimeStamp"
| project TimeGenerated, Resource, Region_s, OperationName, properties_s, Level