// Author: Microsoft Azure
// Display name: Lock contention
// Description: Search for lock contention. It requires log_lock_waits=ON and depends on deadlock_timeout setting.
// Categories: Workloads
// Resource types: Azure Database for PostgreSQL servers
// Topic: Diagnostics

AzureDiagnostics
| where ResourceProvider =="MICROSOFT.DBFORPOSTGRESQL" 
| where Message contains "still waiting for ShareLock on transaction"