// Author: Microsoft Azure
// Display name: Workload continously hitting CPU limits
// Description: Intelligent insights report detecting the workload behavor as continously hitting CPU limits. Please note that SQLInsights log needs to be enabled for each database monitored.
// Categories: IT & Management Tools
// Resource types: SQL managed instances
// Topic: Intelligent insights

let alert_run_interval = 1h;
let insights_string = "hitting its CPU limits";
AzureDiagnostics
| where Category == "SQLInsights" and status_s == "Active"
| where TimeGenerated > ago(alert_run_interval)
| where rootCauseAnalysis_s contains insights_string
| distinct _ResourceId