// Author: Microsoft Azure
// Display name: Publish failures by domain and error
// Description: Publish failures logs by domain name and error message.
// Categories: Azure Resources
// Resource types: Event Grid Domains
// Topic: Diagnostics

AegPublishFailureLogs 
| parse Message with * "), httpStatusCode=" HttpStatusCode "," * ", errorMessage=" ErrorMessage 
| parse _ResourceId with * "/domains/" DomainName
| project TimeGenerated, _ResourceId, DomainName, TenantId, OperationName, HttpStatusCode, ErrorMessage
| summarize by _ResourceId, DomainName, HttpStatusCode, ErrorMessage