// Author: Microsoft Azure
// Display name: Successful tasks per job
// Description: Provides the number of successful tasks per job.
// Categories: Azure Resources
// Resource types: Batch accounts
// Topic: Tasks

AzureDiagnostics
| where OperationName=="TaskCompleteEvent"
| where executionInfo_exitCode_d==0 // Your application may use an exit code other than 0 to denote a successful operation
| summarize successfulTasks=count(id_s) by jobId=jobId_s