// Author: Microsoft Azure
// Display name: Task durations
// Description: Gives the elapsed time of tasks in seconds, from task start to task complete.
// Categories: Azure Resources
// Resource types: Batch accounts
// Topic: Tasks

AzureDiagnostics
| where OperationName=="TaskCompleteEvent"
| extend taskId=id_s, ElapsedTime=datetime_diff('second', executionInfo_endTime_t, executionInfo_startTime_t) // For longer running tasks, consider changing 'second' to 'minute' or 'hour'
| summarize taskList=make_list(taskId) by ElapsedTime