// Author: Microsoft Azure
// Display name: Recently connected devices
// Description: List of devices that IoT Hub saw connect in the specified time period.
// Categories: Azure Resources
// Resource types: IoT Hub
// Topic: Usage

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.DEVICES" and ResourceType == "IOTHUBS"
| where Category == "Connections" and OperationName == "deviceConnect"
| extend DeviceId = tostring(parse_json(properties_s).deviceId)
| summarize max(TimeGenerated) by DeviceId, _ResourceId