// Author: Microsoft Azure
// Display name: Total agent latency timechart, last day
// Description: Chart the median (50th percentile) agent latency over the last day.
// Categories: monitor
// Resource types: Azure Monitor
// Solutions: LogManagement
// Topic: Health

union *
| where TimeGenerated > ago(1d)
| extend AgentLatencySeconds = (_TimeReceived-TimeGenerated)/1s
| summarize percentile(AgentLatencySeconds, 50) by bin(TimeGenerated,1h)
| render timechart 