// Author: Microsoft Azure
// Display name: Backend latency
// Description: Statistics of time (in miliseconds) spent in backend IO.
// Categories: Azure Resources
// Resource types: API Management services
// Topic: Latency

ApiManagementGatewayLogs
| where TimeGenerated > ago(1d)
| summarize Average=avg(BackendTime), Median=percentile(BackendTime, 50), 90th_Percentile=percentile(BackendTime, 90) by bin(TimeGenerated, 15m) 
| render timechart