// Author: Microsoft Azure
// Display name: Client latency
// Description: Statistics of time (in miliseconds) spent in client IO.
// Categories: Azure Resources
// Resource types: API Management services
// Topic: Latency

ApiManagementGatewayLogs
| where TimeGenerated > ago(1d)
| summarize Average=avg(ClientTime), Median=percentile(ClientTime, 50), 90th_Percentile=percentile(ClientTime, 90) by bin(TimeGenerated, 15m) 
| render timechart