// Author: Microsoft Azure
// Display name: Request errors by user agent
// Description: Count number of requests with error responses by user agent.
// Categories: Network
// Resource types: Front Doors
// Topic: Errors

// Summarize number of requests per user agent and status codes >= 400
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.NETWORK" and Category == "FrontdoorAccessLog"
| where isReceivedFromClient_b == true
| where toint(httpStatusCode_s) >= 400
| summarize RequestCount = count() by UserAgent = userAgent_s, StatusCode = httpStatusCode_s , Resource
| order by RequestCount desc