// Author: aliyoussefi
// Display name: Power Platform Admin Center Analytics - API Pass Rate
// Description: Percentage of API successfulness over a given amount of time. Variables are datetime
// Categories: Power Platform Admin Center Analytics
// Resource types: Dataverse
// Topic: API
requests
| where timestamp between (_fromStartTime .. _toEndTime) //datetime
| summarize CountFailed = countif(success == false), Count = count()
| project round(100.0 * (Count - CountFailed) / Count, 2)