// Author: Microsoft Azure
// Display name: Feature Update Pause Configurations
// Description: Count devices by feature update pause configurations.
// Categories: desktopanalytics
// Solutions: WaaSUpdateInsights
// Topic: Diagnostics

WaaSUpdateStatus
| summarize arg_max(TimeGenerated, *) by ComputerID
| project TimeGenerated, ComputerID, FeaturePauseState
| summarize dcount(ComputerID) by FeaturePauseState