// Author: Microsoft Azure
// Display name: Total billable executions
// Description: Total billable executions by operation name.
// Categories: Azure Resources
// Resource types: Logic Apps
// Topic: Costing

// Total billable executions
AzureDiagnostics
| where ResourceProvider == "MICROSOFT.LOGIC"
| where Category == "WorkflowRuntime" 
| where OperationName has "workflowTriggerStarted" or OperationName has "workflowActionStarted" 
| summarize dcount(resource_runId_s) by OperationName, resource_workflowName_s