// Author: Microsoft Azure
// Display name: Cache hit ratio
// Description: Statistics of Cache hit/miss ratio.
// Categories: Azure Resources
// Resource types: API Management services
// Topic: Diagnostics

ApiManagementGatewayLogs
| where TimeGenerated > ago(1d)
| summarize Cache_Miss=countif(Cache  == "miss"), Cache_Hit=countif(Cache == "hit") by bin(TimeGenerated, 15m)
| extend Ratio=Cache_Hit / (Cache_Hit + Cache_Miss)
| project-away Cache_Hit , Cache_Miss 
| render timechart