// Author: Microsoft Azure
// Display name: GetFailedChannelsToBotRequests
// Description: Gets a distinct list of all the unsuccessful requests to bot from channels.
// Categories: Azure Resources
// Resource types: Bot Services
// Topic: Diagnostics

ABSBotRequests
| where TimeGenerated > ago(12h)
| where ResultCode !startswith "2"
| where Category == 'ABSChannelToBotRequests'
| sort by TimeGenerated desc