// Author: Microsoft Azure
// Display name: Container CPU
// Description: View all the container CPU usage averaged over 30mins.
// Categories: Containers,Azure Resources
// Resource types: Kubernetes services
// Topic: Performance

//Select the Line chart display option: can we calculate percentage?
Perf
| where ObjectName == "K8SContainer" and CounterName == "cpuUsageNanoCores"
| summarize AvgCPUUsageNanoCores = avg(CounterValue) by bin(TimeGenerated, 30m), InstanceName, _ResourceId