// Author: Microsoft Azure
// Display name: Request sizes
// Description: Statistics of request sizes in the last 24 hours.
// Categories: Azure Resources
// Resource types: API Management services
// Topic: Usage

ApiManagementGatewayLogs
| where TimeGenerated > ago(1d)
| summarize Average=avg(RequestSize), Median=percentile(RequestSize, 50), 90th_Percentile=percentile(RequestSize, 90) by bin(TimeGenerated, 5m) 
| render timechart