// Author: Microsoft Azure
// Display name: Azure Automation jobs that are Completed
// Description: List all automation jobs that got completed.
// Categories: Azure Resources
// Resource types: Automation accounts
// Topic: Automation Jobs

AzureDiagnostics 
| where ResourceProvider == "MICROSOFT.AUTOMATION" and Category == "JobLogs" and ResultType == "Completed" 
| project TimeGenerated , RunbookName_s , ResultType , _ResourceId , JobId_g