// Author: Microsoft Azure
// Display name: Runbook completed successfully with errors
// Description: List all jobs that completed with errors.
// Categories: Azure Resources
// Resource types: Automation accounts
// Topic: Automation Jobs

AzureDiagnostics 
| where ResourceProvider == "MICROSOFT.AUTOMATION" and Category == "JobStreams" and StreamType_s == "Error" 
| project TimeGenerated , RunbookName_s , StreamType_s , _ResourceId , ResultDescription , JobId_g