// Author: Microsoft Azure
// Display name: Missing critical security updates
// Description: All computers that are missing critical updates or security updates.
// Categories: IT & Management Tools
// Resource types: Virtual machines
// Solutions: Updates
// Topic: Diagnostics

Update
|where  OSType != "Linux" and UpdateState == "Needed" and Optional == "false" and (Classification == "Security Updates" or Classification == "Critical Updates") 
| sort by TimeGenerated desc