// Author: Microsoft Azure
// Display name: Container Lifecycle Information
// Description: List all of a container's lifecycle information.
// Categories: Containers,Azure Resources
// Resource types: Kubernetes services
// Solutions: ContainerInsights
// Topic: Audit

ContainerInventory
| project Computer, Name, Image, ImageTag, ContainerState, CreatedTime, StartedTime, FinishedTime
| top 200 by FinishedTime desc