// Author: Microsoft Azure
// Display name: List all input deserialization errors
// Description: Shows errors caused due to malformed events that could not be deserialized by the job.
// Categories: Security
// Resource types: Key vaults
// Topic: Input data Errors

AzureDiagnostics
| where ResourceProvider == "MICROSOFT.STREAMANALYTICS" and parse_json(properties_s).DataErrorType in ("InputDeserializerError.InvalidData", "InputDeserializerError.TypeConversionError", "InputDeserializerError.MissingColumns", "InputDeserializerError.InvalidHeader", "InputDeserializerError.InvalidCompressionType")
| project TimeGenerated, Resource, Region_s, OperationName, properties_s, Level, _ResourceId